### ISSUE TITLE
LDPC matrix is really huge

### ISSUE THREAD

**Issue by MohammedAhmedMagzoub** [yokian/ldpc-enc-dec#1]
The H matrix that you are using it is really huge is there any way to use small H matrix with this code I tried but I couldnot get it.

**Comment by jeappen** [comment]
Hi Mohammed,

This code was mainly to benchmark the performance of the DVB-S2 standard LDPC matrix with pseudo random puncturing to vary code rates. Since most actual applications involve large LDPC matrices, I haven't tested the code with small ones although you should be able to insert it by checking the usage of the function pseudorand_puncturing_anyrate_no_H_modification.m in the encode and decode functions.

dvbs2ldpc() is a function in matlab that creates the H matrix for you, you may want to check it out.

- Joe
